version: '3'

services:
  sdk:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
    command: sh -c "cd examples && go run main.go"

# To run:
# 1. Copy .env.example to .env and update with your values
# 2. Run: docker-compose up 